---
version: '3'
services:
  webapp:
    image: "registry.gitlab.com/nekonaq.docker/webapp:$WEBAPP_VERSION"
    environment:
      DJANGO_PROJECT_NAME: "$COMPOSE_PROJECT_NAME"
      EXPOSE_HTTP: $EXPOSE_HTTP
    volumes:
      # NOTE: 設定を変更したければ以下をコメントアウトして設定ファイルを編集する。
      # - ./config:/app/config:ro
      - ./data:/app/data
    command: [bin/runuwsgi, -e, local]
    network_mode: host
