---
version: '3'
services:
  webapp:
    image: "registry.gitlab.com/nekonaq.docker/webapp:$WEBAPP_VERSION"
    environment:
      DJANGO_PROJECT_NAME: "$COMPOSE_PROJECT_NAME"
      DJANGO_ENVIRONMENT: "$DJANGO_ENVIRONMENT"
      EXPOSE_HTTP: $EXPOSE_HTTP
    volumes:
      - ./secrets-develop:/app/secrets-develop:ro
      - ./data:/app/data
    command: [bin/runuwsgi]
    network_mode: host
